// Generated by scripts/migrate-content.mjs from the original index.html — do not hand-edit lightly.
import type { Category } from "./schema";

export const CATEGORIES: Category[] = [
  {
    id: "akutt",
    label: "Akutturologi",
    swatch: "sw-akutt",
    badgeLabel: "Akutt",
  },
  {
    id: "benigne",
    label: "Benigne tilstander",
    swatch: "sw-benign",
    badgeLabel: "Benign",
  },
  {
    id: "maligne",
    label: "Maligne tilstander",
    swatch: "sw-malign",
    badgeLabel: "Malign",
  },
  {
    id: "kirurgi",
    label: "Operasjonsteknikker",
    swatch: "sw-kirurgi",
    badgeLabel: "Operasjonsteknikk",
  },
  {
    id: "admin",
    label: "Henvisningsvurdering",
    swatch: "sw-admin",
    badgeLabel: "Administrativt",
  },
  {
    id: "om",
    label: "Om siden",
    swatch: "sw-benign",
    badgeLabel: "Om siden",
  },
];
