// Generated by scripts/migrate-content.mjs from the original index.html — do not hand-edit lightly.
import type { Topic } from "./schema";

export const TOPICS: Topic[] = [
  {
    id: "urinretensjon-akutt",
    cat: "akutt",
    title: "Akutt urinretensjon",
    status: "ferdig",
    icd: "R33.9",
    komp: [
      {
        label: "SPK",
        count: 10,
      },
    ],
    contentType: "simple",
  },
  {
    id: "priapisme",
    cat: "akutt",
    title: "Priapisme",
    status: "ferdig",
    icd: "N48.3",
    contentType: "simple",
  },
  {
    id: "penisfraktur",
    cat: "akutt",
    title: "Penisfraktur",
    status: "ferdig",
    icd: "S39.848 / N48.8",
    contentType: "simple",
  },
  {
    id: "fourniers-gangren",
    cat: "akutt",
    title: "Fourniers gangren",
    status: "ferdig",
    icd: "N49.3",
    contentType: "simple",
  },
  {
    id: "blaretamponade",
    cat: "akutt",
    title: "Blæretamponade (koagelretensjon)",
    status: "ferdig",
    icd: "N32.8 / R31.9",
    contentType: "simple",
  },
  {
    id: "via-falsa",
    cat: "akutt",
    title: "Via falsa (falsk urinrørskanal)",
    status: "ferdig",
    icd: "N99.8 / T83.5",
    contentType: "simple",
  },
  {
    id: "bph",
    cat: "benigne",
    title: "Benign prostatahyperplasi (BPH)",
    status: "ferdig",
    icd: "N40",
    contentType: "simple",
  },
  {
    id: "nyrestein",
    cat: "benigne",
    title: "Urolithiasis / nyrestein",
    status: "ferdig",
    icd: "N20",
    komp: [
      {
        label: "ESWL",
        count: 5,
      },
    ],
    contentType: "simple",
  },
  {
    id: "oab",
    cat: "benigne",
    title: "Overaktiv blære / LUTS",
    status: "ferdig",
    icd: "N39.4",
    komp: [
      {
        label: "Urodyn tolket",
        count: 20,
      },
      {
        label: "Urodyn utført",
        count: 5,
      },
    ],
    contentType: "simple",
  },
  {
    id: "fimose",
    cat: "benigne",
    title: "Fimose og balanitt",
    status: "ferdig",
    icd: "N47 / N48.1",
    contentType: "simple",
  },
  {
    id: "hydrocele",
    cat: "benigne",
    title: "Hydrocele og varikocele",
    status: "ferdig",
    icd: "N43.3 / I86.1",
    contentType: "simple",
  },
  {
    id: "epididymitt",
    cat: "benigne",
    title: "Epididymitt / akutt skrotum",
    status: "ferdig",
    icd: "N45 / N44",
    contentType: "simple",
  },
  {
    id: "ed",
    cat: "benigne",
    title: "Erektil dysfunksjon",
    status: "ferdig",
    icd: "N48.4",
    contentType: "simple",
  },
  {
    id: "nevrogen",
    cat: "benigne",
    title: "Nevrogen blære",
    status: "ferdig",
    icd: "N31",
    contentType: "simple",
  },
  {
    id: "bekkensmerter",
    cat: "benigne",
    title: "Bekkensmerter / smertefullt blæresyndrom",
    status: "ferdig",
    icd: "R10.2",
    komp: [
      {
        label: "Bekkensentermøte",
        count: 20,
      },
    ],
    contentType: "simple",
  },
  {
    id: "stressinkontinens",
    cat: "benigne",
    title: "Stressinkontinens",
    status: "ferdig",
    icd: "N39.3",
    contentType: "simple",
  },
  {
    id: "urinrorsstriktur",
    cat: "benigne",
    title: "Urinrørsstriktur",
    status: "ferdig",
    icd: "N35.8",
    komp: [
      {
        label: "Diureserenografi",
        count: 1,
      },
    ],
    contentType: "simple",
  },
  {
    id: "prostatakreft",
    cat: "maligne",
    title: "Prostatakreft",
    status: "ferdig",
    icd: "C61",
    contentType: "simple",
  },
  {
    id: "blarekreft",
    cat: "maligne",
    title: "Blærekreft (urotelialt karsinom)",
    status: "ferdig",
    icd: "C67",
    contentType: "simple",
  },
  {
    id: "nyrekreft",
    cat: "maligne",
    title: "Nyrekreft (RCC)",
    status: "ferdig",
    icd: "C64",
    contentType: "simple",
  },
  {
    id: "testikkelkreft",
    cat: "maligne",
    title: "Testikkelkreft",
    status: "ferdig",
    icd: "C62",
    contentType: "simple",
  },
  {
    id: "peniskreft",
    cat: "maligne",
    title: "Peniskreft",
    status: "ferdig",
    icd: "C60",
    contentType: "simple",
  },
  {
    id: "ovreurotelial",
    cat: "maligne",
    title: "Øvre urotelial kreft",
    status: "ferdig",
    icd: "C65 / C66",
    contentType: "simple",
  },
  {
    id: "ralp",
    cat: "kirurgi",
    title: "RALP — Robotassistert prostatektomi",
    status: "ferdig",
    komp: [
      {
        label: "Prostatektomi",
        count: 10,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Kirurgisk radikalbehandling ved lokalisert/lokalavansert prostatakreft der pasienten er kandidat for kurativ behandling — se risikogruppering under Prostatakreft.</div>',
  },
  {
    id: "turp",
    cat: "kirurgi",
    title: "TURP",
    status: "ferdig",
    ncsp: "KED22",
    icd: "N40",
    komp: [
      {
        label: "TUR-P",
        count: 70,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>BPH med LUTS refraktær mot medikamenter, residiverende retensjon/UVI/hematuri/blæresten, eller obstruktiv nyresvikt. Se BPH.</div>',
  },
  {
    id: "turbt",
    cat: "kirurgi",
    title: "TURB",
    status: "ferdig",
    ncsp: "KCD02",
    icd: "C67",
    komp: [
      {
        label: "TUR-B",
        count: 70,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Diagnostikk og behandling av blæretumor — både initial reseksjon og re-TURB ved høyrisiko NMIBC. Se Blærekreft.</div>',
  },
  {
    id: "nefrektomi",
    cat: "kirurgi",
    title: "Nefrektomi (radikal/partiell)",
    status: "ferdig",
    komp: [
      {
        label: "Åpne nyrer",
        count: 5,
      },
      {
        label: "Lap nyrer",
        count: 5,
      },
      {
        label: "Nefroureterektomi",
        count: 3,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Nyrecellekarsinom iht. stadium — se Nyrekreft. Partiell (nefronsparende) foretrekkes der teknisk mulig.</div>',
  },
  {
    id: "rirs",
    cat: "kirurgi",
    title: "Ureterorenoskopi / RIRS",
    status: "ferdig",
    ncsp: "KBE12, KBV02",
    icd: "N20.1",
    komp: [
      {
        label: "URS",
        count: 50,
      },
      {
        label: "Fleksibel URS",
        count: 15,
      },
      {
        label: "JJ-stent",
        count: 30,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Ureterstein, nyrebekkenstein &lt;2 cm, samt diagnostikk/behandling av øvre urotelial tumor.</div>',
  },
  {
    id: "pcnl",
    cat: "kirurgi",
    title: "PCNL",
    status: "ferdig",
    komp: [
      {
        label: "PCN",
        count: 5,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Store nyresteiner (&gt;2 cm), komplekse steinbyrder (koralsteiner), eller steiner uegnet for RIRS/ESWL.</div>',
  },
  {
    id: "cystektomi",
    cat: "kirurgi",
    title: "Cystektomi og urinavledning",
    status: "ferdig",
    komp: [
      {
        label: "Cystektomi",
        count: 5,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Muskelinvasiv blærekreft (MIBC), BCG-refraktær høyrisiko NMIBC, eller andre bekkenmaligniteter med blæreinnvekst.</div>',
  },
  {
    id: "sirkumsisjon",
    cat: "kirurgi",
    title: "Sirkumsisjon",
    status: "ferdig",
    ncsp: "KGH10",
    icd: "N47",
    komp: [
      {
        label: "Fimose",
        count: 15,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Patologisk fimose (BXO/lichen sclerosus, arrdannelse), residiverende balanitt/parafimose. Religiøs/kulturell ønske er en vanlig henvisningsårsak. Alternativ til full sirkumsisjon er dorsal spalting — begge alternativ bør presenteres for pasienten.</div>',
  },
  {
    id: "vasektomi",
    cat: "kirurgi",
    title: "Vasektomi",
    status: "ferdig",
    komp: [
      {
        label: "Vasektomi",
        count: 5,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Permanent, elektiv mannlig sterilisering.</div>',
  },
  {
    id: "orkidopeksi",
    cat: "kirurgi",
    title: "Orkiopeksi",
    status: "ferdig",
    ncsp: "KFH10",
    icd: "Q53.1",
    komp: [
      {
        label: "Orkiopeksi",
        count: 10,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Retentio testis (udescendert testikkel) hos gutt, eller fiksasjon etter detorkvering ved testistorsjon (da bilateralt, se Epididymitt/akutt skrotum og Operasjonsteknikker — Detorkvering).</div>',
  },
  {
    id: "testistorsjon-op",
    cat: "kirurgi",
    title: "Detorkvering og fiksasjon ved testistorsjon",
    status: "ferdig",
    ncsp: "KFH20, KFH10",
    icd: "N44",
    komp: [
      {
        label: "Scrotalekspl",
        count: 10,
        note: "omtrentlig — portalen spesifiserer «scrotal eksplorasjon» generelt, ikke isolert testistorsjon",
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout high"><b>Akutt kirurgisk emergency</b>Ved klinisk mistanke om testistorsjon skal eksplorasjon ikke forsinkes av bildediagnostikk. Se Epididymitt/akutt skrotum for differensialdiagnostikk.</div>',
  },
  {
    id: "intern-uretrotomi",
    cat: "kirurgi",
    title: "Intern uretrotomi",
    status: "ferdig",
    ncsp: "KDV12, KCX20",
    icd: "N35.8",
    komp: [
      {
        label: "Intern uretrotomi",
        count: 10,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Skopiverifisert, primær kort urinrørsstriktur. Førstevalg i behandlingsstigen — se Urinrørsstriktur for videre forløp ved residiv (Optilume/åpen uretraplastikk).</div>',
  },
  {
    id: "botox-blare",
    cat: "kirurgi",
    title: "Botulinumtoksin (Botox) i blære",
    status: "ferdig",
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>OAB (med/uten lekkasje) uten adekvat effekt av full peroral blæredempende behandling, eller uakseptable bivirkninger. Også aktuelt ved smertefullt blæresyndrom (PBS) uten Hunnerske sår og manglende effekt av instillasjon/medikamenter — se Bekkensmerter.</div>\n<div class="callout internal"><b>Ahus internt — urologisk poliklinikk</b>Doser og oppfølgingsrutine under er lokal prosedyre ved Ahus (internt undervisningsmateriale, sist endret sept. 2024).</div>',
  },
  {
    id: "snm",
    cat: "kirurgi",
    title: "Sakral nervemodulasjon (SNM)",
    status: "ferdig",
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>OAB med/uten lekkasje uten adekvat effekt av full peroral blæredempende behandling, eller uakseptable bivirkninger.</div>\n<div class="callout high"><b>Kontraindikasjoner</b>Manglende compliance, høy alder, interstitiell cystitt/smertefullt blæresyndrom, progressiv nevrologisk lidelse (relativ), diabetes (relativ). Compliance vurderes strengt: kognisjon, samarbeidsevne og språk (tolk aksepteres hvis dette fungerer godt).</div>\n<div class="callout internal"><b>Ahus internt — urologisk poliklinikk</b>Prosedyren under er lokal praksis ved Ahus (internt undervisningsmateriale, sist endret sept. 2024).</div>',
  },
  {
    id: "optilume",
    cat: "kirurgi",
    title: "Optilume (medikamentavgivende ballongdilatasjon)",
    status: "ferdig",
    ncsp: "KDH62, KUD02",
    icd: "N35.8",
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Residiv urinrørsstriktur i bulbære uretra, verifisert &lt;3 cm og passabel med guidewire ved poliklinisk cystoskopi — som alternativ til ny intern uretrotomi eller åpen uretraplastikk etter residiv av første intern uretrotomi. Se Urinrørsstriktur.</div>\n<div class="callout internal"><b>Ahus internt</b>Utføres ved DKS Ski. Grønnskjema: operasjonskode «U Optilume», behandlingssted Ski sykehus.</div>',
  },
  {
    id: "cystolitotripsi",
    cat: "kirurgi",
    title: "Cystolitotripsi",
    status: "ferdig",
    ncsp: "KCE02",
    icd: "N21.0",
    komp: [
      {
        label: "Cystolithotripsi",
        count: 5,
      },
      {
        label: "Cystotomi, TVP",
        count: 5,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Symptomgivende eller tilfeldig påvist blærestein.</div>',
  },
  {
    id: "hydrocelectomi",
    cat: "kirurgi",
    title: "Hydrocelectomi ad modum Winkelmann",
    status: "ferdig",
    ncsp: "KFD20",
    icd: "N43.3",
    komp: [
      {
        label: "Hydrocele",
        count: 10,
      },
      {
        label: "Spermatocele",
        count: 5,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Symptomgivende hydrocele og pasientens ønske om operasjon. Se Hydrocele og varikocele for utredning.</div>',
  },
  {
    id: "orkiektomi",
    cat: "kirurgi",
    title: "Orkiektomi (unilateral)",
    status: "ferdig",
    ncsp: "KFC00",
    icd: "C62 / N51.1",
    komp: [
      {
        label: "Orkiektomi",
        count: 10,
      },
    ],
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Malignitetssuspekt testistumor. Se Testikkelkreft for utredning — markører (AFP, hCG, LD), skrotal UL og CT thorax/abdomen/bekken skal foreligge, og sædbanking skal være tilbudt <strong>før</strong> operasjon.</div>',
  },
  {
    id: "penisplastikk",
    cat: "kirurgi",
    title: "Penisplastikk (Peyronies sykdom)",
    status: "ferdig",
    ncsp: "KGH20",
    icd: "N48.6",
    contentType: "toggle",
    indication:
      '<div class="callout"><b>Indikasjon</b>Peyronies sykdom (induratio penis plastica) med signifikant krumning som hindrer samleie, i stabil fase av sykdommen.</div>\n<div class="callout amber"><b>Viktig forventningsavklaring</b>Pasienten må informeres om at fullstendig korreksjon av feilstillingen ikke kan loves — målet er tilstrekkelig retting til å muliggjøre samleie, samt at inngrepet kan gi noe forkortning av penis.</div>',
  },
  {
    id: "inkontinenskirurgi",
    cat: "kirurgi",
    title: "Midturetral slynge og kunstig urinsfinkter",
    status: "ferdig",
    icd: "N39.3",
    contentType: "simple",
  },
  {
    id: "henvisningsvurdering",
    cat: "admin",
    title: "Prioritering av henvisninger",
    status: "ferdig",
    contentType: "simple",
  },
  {
    id: "om-siden",
    cat: "om",
    title: "Om siden og kilder",
    status: "ferdig",
    contentType: "simple",
  },
];
