// Generated by scripts/migrate-content.mjs from the original index.html — do not hand-edit lightly.
import type { Topic } from "./schema";

export const TOPICS: Topic[] = [
  {
    id: "urinretensjon-akutt",
    cat: "akutt",
    title: "Akutt urinretensjon",
    status: "ferdig",
    icd: "R33.9",
    contentType: "tabs",
    tabs: [
      { id: "retensjon", label: "Urinretensjon" },
      { id: "via-falsa", label: "Via falsa" },
    ],
    summary:
      "Plutselig, smertefull manglende evne til å tømme blæren — krever umiddelbar avlastning med kateter.",
  },
  {
    id: "priapisme",
    cat: "akutt",
    title: "Priapisme",
    status: "ferdig",
    icd: "N48.3",
    contentType: "simple",
    summary:
      "Vedvarende, uønsket ereksjon uten seksuell stimulering — ved ischemisk type en akutt urologisk nødsituasjon.",
  },
  {
    id: "penisfraktur",
    cat: "akutt",
    title: "Penisfraktur",
    status: "ferdig",
    icd: "S39.848 / N48.8",
    contentType: "simple",
    summary:
      "Ruptur av tunica albuginea i corpus cavernosum, oftest under samleie, med akutt smerte og hevelse.",
  },
  {
    id: "fourniers-gangren",
    cat: "akutt",
    title: "Fourniers gangren",
    status: "ferdig",
    icd: "N49.3",
    contentType: "simple",
    summary:
      "Raskt progredierende, nekrotiserende bløtvevsinfeksjon i genitalia/perineum med høy mortalitet ubehandlet.",
  },
  {
    id: "blaretamponade",
    cat: "akutt",
    title: "Blæretamponade (koagelretensjon)",
    status: "ferdig",
    icd: "N32.8 / R31.9",
    contentType: "simple",
    summary: "Blæren fylles av koagler etter kraftig blødning, slik at urinen ikke kommer ut.",
  },
  {
    id: "testistorsjon",
    cat: "akutt",
    title: "Testistorsjon",
    status: "ferdig",
    contentType: "simple",
    summary:
      "Torsjon av spermatstrengen med avklemt blodforsyning — tidskritisk kirurgisk emergency.",
  },
  {
    id: "urosepsis",
    cat: "akutt",
    title: "Urosepsis / obstruktiv pyelonefritt",
    status: "ferdig",
    contentType: "simple",
    summary:
      "Sepsis fra en obstruert, infisert urinvei — krever akutt avlastning i tillegg til antibiotika.",
  },
  {
    id: "nyretraume",
    cat: "akutt",
    title: "Traumatisk nyreblødning (nyretraume)",
    status: "ferdig",
    icd: "S37.0",
    contentType: "simple",
    summary:
      "Nyreskade etter buk-/flanketraume, gradert med AAST — hemodynamisk stabilitet styrer håndteringen, ikke skadegrad alene.",
  },
  {
    id: "urinom",
    cat: "akutt",
    title: "Urinom (postoperativt/traumatisk)",
    status: "ferdig",
    icd: "N28.8",
    contentType: "simple",
    summary:
      "Urinsamling utenfor urinveiene etter skade på samlesystemet — kirurgisk eller traumatisk.",
  },
  {
    id: "bph",
    cat: "benigne",
    title: "Benign prostatahyperplasi (BPH)",
    status: "ferdig",
    icd: "N40",
    contentType: "simple",
    summary:
      "Godartet forstørrelse av prostata som kan gi obstruktive og irritative vannlatingsplager.",
  },
  {
    id: "nyrestein",
    cat: "benigne",
    title: "Urolithiasis / nyrestein",
    status: "ferdig",
    icd: "N20",
    komp: [
      {
        label: "ESWL",
        count: 5,
      },
    ],
    contentType: "simple",
    summary: "Steindannelse i urinveiene som kan gi kolikksmerter, obstruksjon og infeksjon.",
  },
  {
    id: "oab",
    cat: "benigne",
    title: "Overaktiv blære / LUTS",
    status: "ferdig",
    icd: "N39.4",
    komp: [
      {
        label: "Urodyn tolket",
        count: 20,
      },
      {
        label: "Urodyn utført",
        count: 5,
      },
    ],
    contentType: "simple",
    summary: "Symptomkompleks med hyppig og/eller presserende vannlating, med eller uten lekkasje.",
  },
  {
    id: "fimose",
    cat: "benigne",
    title: "Fimose og balanitt",
    status: "ferdig",
    icd: "N47 / N48.1",
    contentType: "simple",
    summary:
      "Trang forhud som ikke lar seg retrahere, ofte kombinert med betennelse i glans/forhud.",
  },
  {
    id: "hydrocele",
    cat: "benigne",
    title: "Hydrocele og varikocele",
    status: "ferdig",
    icd: "N43.3 / I86.1",
    contentType: "simple",
    summary: "Væskeansamling rundt testikkelen, eller utvidede vener i pungen (varikocele).",
  },
  {
    id: "epididymitt",
    cat: "benigne",
    title: "Epididymitt",
    status: "ferdig",
    icd: "N45 / N44",
    contentType: "simple",
    summary:
      "Betennelse i bitestikkelen — en viktig differensialdiagnose til testistorsjon ved akutte skrotalsmerter.",
  },
  {
    id: "ed",
    cat: "benigne",
    title: "Erektil dysfunksjon",
    status: "ferdig",
    icd: "N48.4",
    contentType: "simple",
    summary:
      "Vedvarende manglende evne til å oppnå eller opprettholde ereksjon tilstrekkelig for samleie.",
  },
  {
    id: "nevrogen",
    cat: "benigne",
    title: "Nevrogen blære",
    status: "ferdig",
    icd: "N31",
    contentType: "simple",
    summary: "Blærefunksjonsforstyrrelse forårsaket av skade eller sykdom i nervesystemet.",
  },
  {
    id: "bekkensmerter",
    cat: "benigne",
    title: "Bekkensmerter / smertefullt blæresyndrom",
    status: "ferdig",
    icd: "R10.2",
    komp: [
      {
        label: "Bekkensentermøte",
        count: 20,
      },
    ],
    contentType: "simple",
    summary: "Kronisk bekkensmerte assosiert med blæren, uten påvisbar infeksjon.",
  },
  {
    id: "stressinkontinens",
    cat: "benigne",
    title: "Stressinkontinens",
    status: "ferdig",
    icd: "N39.3",
    contentType: "simple",
    summary:
      "Ufrivillig urinlekkasje ved fysisk anstrengelse, hoste eller nysing, grunnet svekket lukkemekanisme.",
  },
  {
    id: "urinrorsstriktur",
    cat: "benigne",
    title: "Urinrørsstriktur",
    status: "ferdig",
    icd: "N35.8",
    komp: [
      {
        label: "Diureserenografi",
        count: 1,
      },
    ],
    contentType: "simple",
    summary: "Innsnevring av urinrøret som gir obstruktiv vannlating.",
  },
  {
    id: "residiverende-uvi",
    cat: "benigne",
    title: "Residiverende urinveisinfeksjon",
    status: "ferdig",
    contentType: "simple",
    summary:
      "≥2 UVI på 6 mnd eller ≥3 på 12 mnd — hos menn alltid å regne som komplisert og bør utredes.",
  },
  {
    id: "nyrecyster",
    cat: "benigne",
    title: "Nyrecyster (Bosniak-klassifisering)",
    status: "ferdig",
    contentType: "simple",
    summary:
      "Vanlig insidentalfunn — Bosniak I-IV stratifiserer malignitetsrisiko og styrer oppfølging.",
  },
  {
    id: "urodynamikk",
    cat: "benigne",
    title: "Urodynamikk",
    status: "ferdig",
    contentType: "simple",
    summary:
      "Trykk-/strømningsmåling av blære og uretra for å objektivere årsak til LUTS/inkontinens.",
  },
  {
    id: "prostatakreft",
    cat: "maligne",
    title: "Prostatakreft",
    status: "ferdig",
    icd: "C61",
    contentType: "tabs",
    tabs: [
      { id: "utredning", label: "Utredning" },
      { id: "behandlingsvalg", label: "Behandlingsvalg" },
      { id: "oppfolging", label: "Oppfølging" },
    ],
    indication:
      '<div class="callout"><b>Kjapt sammendrag</b>Prostatakreft er den vanligste kreftformen hos menn i Norge. De fleste tilfeller er lokalisert og langsomtvoksende. Utredning bygger på PSA → bpMR/mpMR prostata → målrettet + systematisk biopsi. Risikogruppering (EAU-modellen) styrer valg mellom aktiv overvåking, kirurgi, stråling og eventuell hormonbehandling.</div>',
    outro:
      '<div class="sources"><h4>Kilder</h4><ul>\n<li>Helsedirektoratet — <a href="https://www.helsedirektoratet.no/retningslinjer/prostatakreft-handlingsprogram" target="_blank">Nasjonalt handlingsprogram for prostatakreft</a>, kap. 5.3 «Bruk av PSA», kap. 5.4 «PSA og arvelig prostatakreft», kap. «Risikoinndeling»/«Bildediagnostisk utredning», og kap. 12.2 «Oppfølgning etter RALP» (sist oppdatert 15. juli 2025)</li>\n<li>EAU Guidelines — Prostate Cancer, uroweb.org</li>\n<li>Internt undervisningsmateriale/presentasjon — «Koelis prosedyre» (biopsibeslutning PSA-tetthet/PI-RADS) og «Kontroll etter prostatektomi»</li>\n<li>Internt MDT-undervisningsmateriale — «Faktorer ved ca prost som diskuteres og dokumenteres på MDT» (AS/WW-kriterier, SPCG15/SPCG19/prePSMA, gentesting)</li>\n<li>Ahus/healthtalk.no/NRK — omtale av Ahus\' pilotprosjekt for prostatakreftscreening (2026–2027)</li>\n</ul></div>\n<div class="disclaimer">Kun til bruk som internt faglig oppslagsverk. Sjekk alltid siste versjon på helsedirektoratet.no og uroweb.org. Biopsi-, kontroll- og MDT-tabellene er transkribert fra fotograferte presentasjonslysbilder/oppslagsark — kontroller mot originalkilde ved operativ bruk.</div>',
    summary: "Den vanligste kreftformen hos menn i Norge, oftest lokalisert og langsomtvoksende.",
  },
  {
    id: "blarekreft",
    cat: "maligne",
    title: "Blærekreft (urotelialt karsinom)",
    status: "ferdig",
    icd: "C67",
    contentType: "tabs",
    tabs: [
      { id: "oversikt", label: "Oversikt" },
      { id: "bcg", label: "BCG-behandling" },
    ],
    indication:
      '<div class="callout"><b>Kjapt sammendrag</b>Over 95 % er urotelialt karsinom. Smertefri makrohematuri er kardinalsymptom. Skillet mellom ikke-muskelinvasiv (NMIBC) og muskelinvasiv (MIBC) sykdom styrer hele behandlingsløpet.</div>',
    outro:
      '<div class="sources"><h4>Kilder</h4><ul><li>Helsedirektoratet — <a href="https://www.helsedirektoratet.no/retningslinjer/blaerekreft-handlingsprogram/oppfolging/oppfolging-av-ikke-muskelinfiltrerende-blaerekreft" target="_blank">Nasjonalt handlingsprogram for blære- og urotelkreft, kap. 10.2: Oppfølging av ikke-muskelinfiltrerende blærekreft</a> (sist oppdatert 24. april 2026)</li><li>Helsedirektoratet — <a href="https://www.helsedirektoratet.no/retningslinjer/blaerekreft-handlingsprogram/initial-behandling-og-behandling-av-nmibc/instillasjonsbehandling-av-nmibc" target="_blank">Nasjonalt handlingsprogram for blære- og urotelkreft, kap. 7.5: Instillasjonsbehandling av NMIBC (BCG)</a> (sist oppdatert 24. april 2026)</li><li>Felleskatalogen — BCG-medac (SPC): virkningsmekanisme, kontraindikasjoner og bivirkninger</li><li>EAU Guidelines — Non-muscle-invasive og Muscle-invasive Bladder Cancer, uroweb.org</li></ul></div><div class="disclaimer">Kun til bruk som internt faglig oppslagsverk. Sjekk alltid siste versjon på helsedirektoratet.no.</div>',
    summary: "Kreft utgått fra urotelet i blæreveggen, ofte debuterende med smertefri hematuri.",
  },
  {
    id: "nyrekreft",
    cat: "maligne",
    title: "Nyrekreft (RCC)",
    status: "ferdig",
    icd: "C64",
    contentType: "simple",
    summary: "Nyrecellekarsinom, ofte tilfeldig oppdaget ved bildediagnostikk av andre årsaker.",
  },
  {
    id: "testikkelkreft",
    cat: "maligne",
    title: "Testikkelkreft",
    status: "ferdig",
    icd: "C62",
    contentType: "simple",
    summary:
      "Den vanligste kreftformen hos unge menn, som oftest debuterer med en palpabel testikkelknute.",
  },
  {
    id: "peniskreft",
    cat: "maligne",
    title: "Peniskreft",
    status: "ferdig",
    icd: "C60",
    contentType: "simple",
    summary: "Sjelden kreftform i penis, ofte assosiert med fimose og HPV.",
  },
  {
    id: "ovreurotelial",
    cat: "maligne",
    title: "Øvre urotelial kreft",
    status: "ferdig",
    icd: "C65 / C66",
    contentType: "simple",
    summary: "Kreft i urotelet i nyrebekken eller ureter.",
  },
  {
    id: "ralp",
    cat: "kirurgi",
    title: "RALP — Robotassistert prostatektomi",
    status: "ferdig",
    komp: [
      {
        label: "Prostatektomi",
        count: 10,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Kirurgisk radikalbehandling ved lokalisert/lokalavansert prostatakreft der pasienten er kandidat for kurativ behandling — se risikogruppering under Prostatakreft.</div>',
    summary: "Robotassistert laparoskopisk radikal prostatektomi ved lokalisert prostatakreft.",
  },
  {
    id: "turp",
    cat: "kirurgi",
    title: "TURP",
    status: "ferdig",
    ncsp: "KED22",
    icd: "N40",
    komp: [
      {
        label: "TUR-P",
        count: 70,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>BPH med LUTS refraktær mot medikamenter, residiverende retensjon/UVI/hematuri/blæresten, eller obstruktiv nyresvikt. Se BPH.</div>',
    summary: "Transuretral reseksjon av prostata — gullstandard kirurgisk behandling av BPH.",
  },
  {
    id: "turbt",
    cat: "kirurgi",
    title: "TURB",
    status: "ferdig",
    ncsp: "KCD02",
    icd: "C67",
    komp: [
      {
        label: "TUR-B",
        count: 70,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Diagnostikk og behandling av blæretumor — både initial reseksjon og re-TURB ved høyrisiko NMIBC. Se Blærekreft.</div>',
    summary: "Transuretral reseksjon av blæretumor, for diagnostikk og behandling av blærekreft.",
  },
  {
    id: "nefrektomi",
    cat: "kirurgi",
    title: "Nefrektomi (radikal/partiell)",
    status: "ferdig",
    komp: [
      {
        label: "Åpne nyrer",
        count: 5,
      },
      {
        label: "Lap nyrer",
        count: 5,
      },
      {
        label: "Nefroureterektomi",
        count: 3,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Nyrecellekarsinom iht. stadium — se Nyrekreft. Partiell (nefronsparende) foretrekkes der teknisk mulig.</div>',
    summary: "Kirurgisk fjerning av hele eller deler av en nyre, oftest ved nyrekreft.",
  },
  {
    id: "rirs",
    cat: "kirurgi",
    title: "Ureterorenoskopi / RIRS",
    status: "ferdig",
    ncsp: "KBE12, KBV02",
    icd: "N20.1",
    komp: [
      {
        label: "URS",
        count: 50,
      },
      {
        label: "Fleksibel URS",
        count: 15,
      },
      {
        label: "JJ-stent",
        count: 30,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Ureterstein, nyrebekkenstein &lt;2 cm, samt diagnostikk/behandling av øvre urotelial tumor.</div>',
    summary: "Fleksibel skopisk stein- og tumorbehandling via urinrøret opp til nyrebekkenet.",
  },
  {
    id: "pcnl",
    cat: "kirurgi",
    title: "PCNL",
    status: "ferdig",
    komp: [
      {
        label: "PCN",
        count: 5,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Store nyresteiner (&gt;2 cm), komplekse steinbyrder (koralsteiner), eller steiner uegnet for RIRS/ESWL.</div>',
    summary: "Steinknusning via en kanal direkte inn i nyren, for store steinbyrder.",
  },
  {
    id: "cystektomi",
    cat: "kirurgi",
    title: "Cystektomi og urinavledning",
    status: "ferdig",
    komp: [
      {
        label: "Cystektomi",
        count: 5,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Muskelinvasiv blærekreft (MIBC), BCG-refraktær høyrisiko NMIBC, eller andre bekkenmaligniteter med blæreinnvekst.</div>',
    summary: "Kirurgisk fjerning av blæren med urinavledning, ved muskelinvasiv blærekreft.",
  },
  {
    id: "sirkumsisjon",
    cat: "kirurgi",
    title: "Sirkumsisjon",
    status: "ferdig",
    ncsp: "KGH10",
    icd: "N47",
    komp: [
      {
        label: "Fimose",
        count: 15,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Patologisk fimose (BXO/lichen sclerosus, arrdannelse), residiverende balanitt/parafimose. Religiøs/kulturell ønske er en vanlig henvisningsårsak. Alternativer til full sirkumsisjon — dorsal spalting, eller ved egnede tilfeller frenulektomi (ved isolert stram frenulum) eller forhudsplastikk (bevarende plastikk der fimosen ikke er uttalt) — bør presenteres for pasienten.</div>',
    summary: "Kirurgisk fjerning av forhuden, oftest ved fimose.",
  },
  {
    id: "vasektomi",
    cat: "kirurgi",
    title: "Vasektomi",
    status: "ferdig",
    komp: [
      {
        label: "Vasektomi",
        count: 5,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Permanent, elektiv mannlig sterilisering.</div>',
    summary: "Kirurgisk avbrytelse av sædlederne for permanent mannlig sterilisering.",
  },
  {
    id: "orkidopeksi",
    cat: "kirurgi",
    title: "Orkiopeksi",
    status: "ferdig",
    ncsp: "KFH10",
    icd: "Q53.1",
    komp: [
      {
        label: "Orkiopeksi",
        count: 10,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Retentio testis (udescendert testikkel) hos gutt, eller fiksasjon etter detorkvering ved testistorsjon (da bilateralt, se Epididymitt og Operasjonsteknikker — Detorkvering).</div>',
    summary: "Kirurgisk nedflytting og fiksasjon av en udescendert testikkel.",
  },
  {
    id: "testistorsjon-op",
    cat: "kirurgi",
    title: "Detorkvering og fiksasjon ved testistorsjon",
    status: "ferdig",
    ncsp: "KFH20, KFH10",
    icd: "N44",
    komp: [
      {
        label: "Scrotalekspl",
        count: 10,
        note: "omtrentlig — portalen spesifiserer «scrotal eksplorasjon» generelt, ikke isolert testistorsjon",
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout high"><b>Akutt kirurgisk emergency</b>Ved klinisk mistanke om testistorsjon skal eksplorasjon ikke forsinkes av bildediagnostikk. Se Epididymitt for differensialdiagnostikk.</div>',
    summary: "Akutt kirurgisk oppretting og fiksering av en vridd testikkel.",
  },
  {
    id: "intern-uretrotomi",
    cat: "kirurgi",
    title: "Intern uretrotomi",
    status: "ferdig",
    ncsp: "KDV12, KCX20",
    icd: "N35.8",
    komp: [
      {
        label: "Intern uretrotomi",
        count: 10,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Skopiverifisert, primær kort urinrørsstriktur. Førstevalg i behandlingsstigen — se Urinrørsstriktur for videre forløp ved residiv (Optilume/åpen uretraplastikk).</div>',
    summary: "Skopisk kløyving av en urinrørsstriktur.",
  },
  {
    id: "botox-blare",
    cat: "kirurgi",
    title: "Botulinumtoksin (Botox) i blære",
    status: "ferdig",
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>OAB (med/uten lekkasje) uten adekvat effekt av full peroral blæredempende behandling, eller uakseptable bivirkninger. Også aktuelt ved smertefullt blæresyndrom (PBS) uten Hunnerske sår og manglende effekt av instillasjon/medikamenter — se Bekkensmerter.</div>\n<div class="callout internal"><b>Ahus internt — urologisk poliklinikk</b>Doser og oppfølgingsrutine under er lokal prosedyre ved Ahus (internt undervisningsmateriale, sist endret sept. 2024).</div>',
    summary:
      "Injeksjon av botulinumtoksin i blæreveggen ved overaktiv blære som ikke svarer på medikamenter.",
  },
  {
    id: "snm",
    cat: "kirurgi",
    title: "Sakral nervemodulasjon (SNM)",
    status: "ferdig",
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>OAB med/uten lekkasje uten adekvat effekt av full peroral blæredempende behandling, eller uakseptable bivirkninger.</div>\n<div class="callout high"><b>Kontraindikasjoner</b>Manglende compliance, høy alder, interstitiell cystitt/smertefullt blæresyndrom, progressiv nevrologisk lidelse (relativ), diabetes (relativ). Compliance vurderes strengt: kognisjon, samarbeidsevne og språk (tolk aksepteres hvis dette fungerer godt).</div>\n<div class="callout internal"><b>Ahus internt — urologisk poliklinikk</b>Prosedyren under er lokal praksis ved Ahus (internt undervisningsmateriale, sist endret sept. 2024).</div>',
    summary:
      "Implantert nervestimulator som modulerer blærefunksjon ved refraktær overaktiv blære.",
  },
  {
    id: "optilume",
    cat: "kirurgi",
    title: "Optilume (medikamentavgivende ballongdilatasjon)",
    status: "ferdig",
    ncsp: "KDH62, KUD02",
    icd: "N35.8",
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Residiv urinrørsstriktur i bulbære uretra, verifisert &lt;3 cm og passabel med guidewire ved poliklinisk cystoskopi — som alternativ til ny intern uretrotomi eller åpen uretraplastikk etter residiv av første intern uretrotomi. Se Urinrørsstriktur.</div>\n<div class="callout internal"><b>Ahus internt</b>Utføres ved DKS Ski. Grønnskjema: operasjonskode «U Optilume», behandlingssted Ski sykehus.</div>',
    summary: "Medikamentavgivende ballongdilatasjon av korte urinrørsstrikturer.",
  },
  {
    id: "cystolitotripsi",
    cat: "kirurgi",
    title: "Cystolitotripsi",
    status: "ferdig",
    ncsp: "KCE02",
    icd: "N21.0",
    komp: [
      {
        label: "Cystolithotripsi",
        count: 5,
      },
      {
        label: "Cystotomi, TVP",
        count: 5,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Symptomgivende eller tilfeldig påvist blærestein.</div>',
    summary: "Skopisk knusning av blærestein.",
  },
  {
    id: "hydrocelectomi",
    cat: "kirurgi",
    title: "Hydrocelectomi ad modum Winkelmann",
    status: "ferdig",
    ncsp: "KFD20",
    icd: "N43.3",
    komp: [
      {
        label: "Hydrocele",
        count: 10,
      },
      {
        label: "Spermatocele",
        count: 5,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Symptomgivende hydrocele og pasientens ønske om operasjon. Se Hydrocele og varikocele for utredning.</div>',
    summary: "Kirurgisk fjerning av hydrocele.",
  },
  {
    id: "orkiektomi",
    cat: "kirurgi",
    title: "Orkiektomi (unilateral)",
    status: "ferdig",
    ncsp: "KFC00",
    icd: "C62 / N51.1",
    komp: [
      {
        label: "Orkiektomi",
        count: 10,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Malignitetssuspekt testistumor. Se Testikkelkreft for utredning — markører (AFP, hCG, LD), skrotal UL og CT thorax/abdomen/bekken skal foreligge, og sædbanking skal være tilbudt <strong>før</strong> operasjon.</div>',
    summary: "Kirurgisk fjerning av en testikkel, oftest ved mistenkt eller påvist testikkelkreft.",
  },
  {
    id: "spk-innleggelse",
    cat: "kirurgi",
    title: "Suprapubisk kateter (SPK)",
    status: "ferdig",
    komp: [
      {
        label: "SPK",
        count: 10,
      },
    ],
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Mislykket eller kontraindisert transuretral kateterisering (urinrørsstriktur, via falsa/falsk kanal, betydelig BPH-obstruksjon), eller planlagt langvarig avlastning uten transuretralt kateter. Se Akutt urinretensjon.</div>',
    summary: "Ultralydveiledet perkutan blæredrenasje når transuretral kateterisering ikke lykkes.",
  },
  {
    id: "penisplastikk",
    cat: "kirurgi",
    title: "Penisplastikk (Peyronies sykdom)",
    status: "ferdig",
    ncsp: "KGH20",
    icd: "N48.6",
    contentType: "toggle",
    hasChecklist: true,
    indication:
      '<div class="callout"><b>Indikasjon</b>Peyronies sykdom (induratio penis plastica) med signifikant krumning som hindrer samleie, i stabil fase av sykdommen.</div>\n<div class="callout amber"><b>Viktig forventningsavklaring</b>Pasienten må informeres om at fullstendig korreksjon av feilstillingen ikke kan loves — målet er tilstrekkelig retting til å muliggjøre samleie, samt at inngrepet kan gi noe forkortning av penis.</div>',
    summary: "Kirurgisk korreksjon av penil krumning ved Peyronies sykdom.",
  },
  {
    id: "inkontinenskirurgi",
    cat: "kirurgi",
    title: "Midturetral slynge og kunstig urinsfinkter",
    status: "ferdig",
    icd: "N39.3",
    contentType: "simple",
    summary: "Kirurgisk behandling av stressinkontinens med slynge eller kunstig lukkemuskel.",
  },
  {
    id: "adrenalektomi",
    cat: "kirurgi",
    title: "Adrenalektomi",
    status: "ferdig",
    contentType: "simple",
    summary: "Kirurgisk fjerning av binyren ved hormonelt aktiv eller malignitetssuspekt tumor.",
  },
  {
    id: "nefroureterektomi",
    cat: "kirurgi",
    title: "Nefroureterektomi",
    status: "ferdig",
    contentType: "simple",
    summary:
      "Fjerning av nyre og hele ureter inkl. blæremansjett, ved høyrisiko øvre urotelial kreft.",
  },
  {
    id: "ureteropyeloplastikk",
    cat: "kirurgi",
    title: "Ureteropyeloplastikk",
    status: "ferdig",
    contentType: "simple",
    summary: "Kirurgisk korreksjon av ureteropelvin overgangsstenose (UPJ-stenose).",
  },
  {
    id: "ureterreimplantasjon",
    cat: "kirurgi",
    title: "Reimplantasjon av ureter",
    status: "ferdig",
    contentType: "simple",
    summary: "Ny innfesting av ureter i blæren ved distal striktur, skade eller refluks.",
  },
  {
    id: "transvesikal-prostatektomi",
    cat: "kirurgi",
    title: "Transvesikal prostatektomi",
    status: "ferdig",
    contentType: "simple",
    summary: "Åpen/robotassistert enukleasjon av svært store, benigne prostataadenomer.",
  },
  {
    id: "kryoablasjon",
    cat: "kirurgi",
    title: "Kryoablasjon (nyre)",
    status: "ferdig",
    contentType: "simple",
    summary:
      "Fryseablasjon av liten nyretumor, som alternativ til reseksjon hos selekterte pasienter.",
  },
  {
    id: "prostataembolisering",
    cat: "kirurgi",
    title: "Embolisering av prostata (PAE)",
    status: "ferdig",
    contentType: "simple",
    hasChecklist: true,
    summary:
      "Kateterbasert embolisering av arteria prostatica ved BPH, som alternativ til kirurgi.",
  },
  {
    id: "antibiotikaprofylakse",
    cat: "kirurgi",
    title: "Antibiotikaprofylakse ved kirurgi",
    status: "ferdig",
    contentType: "simple",
    summary: "Anbefalt antibiotikaprofylakse per inngrepstype ved urologisk kirurgi.",
  },
  {
    id: "henvisningsvurdering",
    cat: "admin",
    title: "Prioritering av henvisninger",
    status: "ferdig",
    contentType: "simple",
    summary: "Veiledning for vurdering og prioritering av henvisninger til urologisk poliklinikk.",
  },
  {
    id: "om-siden",
    cat: "om",
    title: "Om siden og kilder",
    status: "ferdig",
    contentType: "simple",
    summary: "Informasjon om formålet med og kildegrunnlaget for dette oppslagsverket.",
  },
];
